### ISSUE TITLE
Fill is not a function - when using with latest mongoose

### ISSUE THREAD

**Issue by rturk** [whitecolor/mongoose-fill#10]
Hi All,
I'm getting the following error after I've updated to Mongoose 4.5.2

**fill is not a function.**

I've done some initial research and this seems to be related to new Promise design used in Mongoose

**Comment by whitecolor** [comment]
I tried 4.5.2 and all tests passed, just with warning 
```
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
```

Probably need to use native promises instead.

**Comment by whitecolor** [comment]
reopen if needed
