### ISSUE TITLE
Work with aggregation

### ISSUE THREAD

**Issue by AeonRush** [whitecolor/mongoose-fill#14]
When I tried to use `mongoose-fill` with `aggregation` 
```javascript
  require('mongoose').model('Art').aggregate([
    {$lookup: {
      from: 'likes',
      localField: '_id',
      foreignField: 'art',
      as: 'likes'
    }},
    {$sort: {_id: -1}},
  ]).fill('likesCount').exec(callback);
``` 
I got an error
```javascript
TypeError: require(...).model(...).aggregate(...).fill is not a function at router.get
```
When I write
```javascript
 require('mongoose').model('Art').find({}).fill('likesCount').exec(callback);
```
all works fine
I think `monggose-fill` not designed for work in this scenario?

**Comment by whitecolor** [comment]
Yes I think that is because mongoose `aggregate` is just a wrapper for native `aggregate` which is not supposed to always return documents, but something else projected.

**Comment by AeonRush** [comment]
Thanks a lot 😄
