### ISSUE TITLE
Current version on NPM fails

### ISSUE THREAD

**Issue by computertechie** [whitecolor/mongoose-fill#4]
The current version available on NPM fails due to a `require('mongoose-fill')` in the index.js file where it should be `require('mongoose')`

I don't see this in the git history on the repo anywhere, so I'm not sure how it happened.

**Comment by whitecolor** [comment]
Not sure what you mean?

**Comment by computertechie** [comment]
Sorry, it was because of an over-zealous Find/Replace in my project. Everything's fine, nothing to see here :D
