### ISSUE TITLE
Any reason why the callback parameter comes last?

### ISSUE THREAD

**Issue by nainy** [whitecolor/mongoose-fill#5]
I was having an issue with the following code:

````
feed.find().select(visibleFields)                
                .fill('moderatedPosts', {limit: 100})
                .fill('postCount')
                .exec();
````

It failed. Gave no error, no nothing. Just failed. However, this version: 

````
feed.find().select(visibleFields)
                .fill('moderatedPosts postCount', {limit: 100})
                .exec();
````

worked fine. 

Then I realized that if the optional parameters aren't supplied, the first one becomes the callback, which wasn't what my code was expecting. This seems to me like a very strange behavior. Wouldn't it be better to have the callback always come first and have all the optional parameters come after it? Any specific reason why this was done?

**Comment by whitecolor** [comment]
Hey there. I think because it is a usual api convention that callback comes last. In your case you want to use `.options` param in you `fill` definition which defines the default option values, look at the last example in docs (readme).

**Comment by whitecolor** [comment]
Will close it, if no question more.
