### ISSUE TITLE
Add a fillAll() to fill all defined fill fields on a model/doc/schema

### ISSUE THREAD

**Issue by computertechie** [whitecolor/mongoose-fill#7]
This would allow for much more model-agnostic code. Possibly have an option for whether to populate nested fields in subdocs (likely depends on #6 )

**Comment by whitecolor** [comment]
Do not get what that mean, you are seeking for very implicit way of doing things, which usually lead to unpredictable results)

**Comment by computertechie** [comment]
Fair enough, simple enough to make a wrapper or such.

I'm more concerned about #6 though, this was just a convenience feature.
